# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "capybara"
gem "minitest"
gem "rack"
gem "rake"
gem "vcr"
gem "webmock"
