require 'rake/testtask'

Rake::TestTask.new do |task|
  # On GitHub Actions CI, gems install under a "vendor" directory in here,
  # so we have to glob our way around that!
  task.test_files = FileList['./{[!vendor/]**/*,*}_test.rb']
  task.verbose = true
end
desc 'Run tests'

task default: :test
